src/src/Entity/Event.php
<?php

namespace App\Entity;

use App\Repository\EventRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EventRepository::class)]
class Event extends Attraction
{
    

    #[ORM\Column(type: 'string', length: 255)]
    public $organizer;

    #[ORM\Column(type: 'datetime_immutable')]
    public $startDateTime;

    #[ORM\Column(type: 'datetime_immutable')]
    public $end_datetime;

    

    public function getOrganizer(): ?string
    {
        return $this->organizer;
    }

    public function setOrganizer(string $organizer): self
    {
        $this->organizer = $organizer;

        return $this;
    }

    public function getStartDateTime(): ?\DateTimeImmutable
    {
        return $this->startDateTime;
    }

    public function setStartDateTime(\DateTimeImmutable $startDateTime): self
    {
        $this->startDateTime = $startDateTime;

        return $this;
    }

    public function getEndDatetime(): ?\DateTimeImmutable
    {
        return $this->end_datetime;
    }

    public function setEndDatetime(\DateTimeImmutable $end_datetime): self
    {
        $this->end_datetime = $end_datetime;

        return $this;
    }
}

src/src/Form/EventType.php
<?php

namespace App\Form;

use App\Entity\Event;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EventType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('shortDescription')
            ->add('fullDescription')
            ->add('score')
            // ->add('createdAt')
            // ->add('updatedAt')
            // ->add('createdUsername')
            // ->add('updatedUsername')
            ->add('organizer')
            ->add('startDateTime')
            ->add('end_datetime')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Event::class,
        ]);
    }
}

src/src/Controller/EventController.php
<?php

namespace App\Controller;

use App\Entity\Event;
use App\Form\EventType;
use App\Repository\EventRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface;
use Symfony\Component\Security\Core\Authentication\Token\TokenInterface;

#[Route('/event')]
class EventController extends AbstractController
{

    /** @var  TokenStorageInterface */
    private $tokenStorage;

    /**
     * @param TokenStorageInterface  $storage
    */
    public function __construct(
        TokenStorageInterface $storage,
    )
    {
        $this->tokenStorage = $storage;
    }

    #[Route('/{_locale}', name: 'app_event_index', methods: ['GET'] , defaults:['_locale'=>'en'], requirements: ['_locale' => 'en|fa'])]
    public function index(EntityManagerInterface $entityManager): Response
    {
        $events = $entityManager
            ->getRepository(Event::class)
            ->findAll();

        return $this->render('event/index.html.twig', [
            'events' => $events,
        ]);
    }

    #[Route('/new', name: 'app_event_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $event = new Event();
        $form = $this->createForm(EventType::class, $event);
        $form->handleRequest($request);
        
        // $event->setCreatedAt(new \DateTimeImmutable('now'));
        // $token = $this->tokenStorage->getToken();
        // if ($token instanceof TokenInterface) {
        //     /** @var User $user */
        //     $user = $token->getUser()->getUserIdentifier();
        //     $event->setCreatedUsername($user);
        // }

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($event);
            $entityManager->flush();

            return $this->redirectToRoute('app_event_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('event/new.html.twig', [
            'event' => $event,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_event_show', methods: ['GET'], requirements: ['id' => '\d+'])]
    public function show(Event $event): Response
    {
        
        return $this->render('event/show.html.twig', [
            'event' => $event,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_event_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Event $event, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(EventType::class, $event);
        $form->handleRequest($request);
        // $event->setUpdatedAt(new \DateTimeImmutable('now'));
        // $token = $this->tokenStorage->getToken();
        // if ($token instanceof TokenInterface) {
        //     /** @var User $user */
        //     $user = $token->getUser()->getUserIdentifier();
        //     $event->setUpdatedUsername($user);
        // }

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_event_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('event/edit.html.twig', [
            'event' => $event,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_event_delete', methods: ['POST'], requirements: ['id' => '\d+'])]
    public function delete(Request $request, Event $event, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$event->getId(), $request->request->get('_token'))) {
            $entityManager->remove($event);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_event_index', [], Response::HTTP_SEE_OTHER);
    }
}

src/templates/event/_delete_form.html.twig
<form method="post" action="{{ path('app_event_delete', {'id': event.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ event.id) }}">
    <button class="btn">Delete</button>
</form>

src/templates/event/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

src/templates/event/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Event{% endblock %}

{% block body %}
    <h1>Edit Event</h1>

    {{ include('event/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_event_index') }}">back to list</a>

    {{ include('event/_delete_form.html.twig') }}
{% endblock %}

src/templates/event/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Event index{% endblock %}

{% block body %}
    <h1>{{'Event index' | trans}}</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>ShortDescription</th>
                <th>FullDescription</th>
                <th>Score</th>
                <th>CreatedAt</th>
                <th>UpdatedAt</th>
                <th>CreatedUsername</th>
                <th>UpdatedUsername</th>
                <th>Organizer</th>
                <th>StartDateTime</th>
                <th>End_datetime</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for event in events %}
            <tr>
                <td>{{ event.id }}</td>
                <td>{{ event.name }}</td>
                <td>{{ event.shortDescription }}</td>
                <td>{{ event.fullDescription }}</td>
                <td>{{ event.score }}</td>
                <td>{{ event.createdAt ? event.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ event.updatedAt ? event.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ event.createdUsername }}</td>
                <td>{{ event.updatedUsername }}</td>
                <td>{{ event.organizer }}</td>
                <td>{{ event.startDateTime ? event.startDateTime|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ event.endDatetime ? event.endDatetime|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_event_show', {'id': event.id}) }}">show</a>
                    <a href="{{ path('app_event_edit', {'id': event.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="13">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_event_new') }}">Create new</a>
{% endblock %}

src/templates/event/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Event{% endblock %}

{% block body %}
    <h1>Create new Event</h1>

    {{ include('event/_form.html.twig') }}

    <a href="{{ path('app_event_index') }}">back to list</a>
{% endblock %}

src/templates/event/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Event{% endblock %}

{% block body %}
    <h1>Event</h1>

    <table class="table">
        <tbody>
            
            <tr>
                <th>Id</th>
                <td>{{ event.id }}</td>
            </tr>
            
            <tr>
                <th>Name</th>
                <td>{{ event.name }}</td>
            </tr>
            <tr>
                <th>ShortDescription</th>
                <td>{{ event.shortDescription }}</td>
            </tr>
            <tr>
                <th>FullDescription</th>
                <td>{{ event.fullDescription }}</td>
            </tr>
            <tr>
                <th>Score</th>
                <td>{{ event.score }}</td>
            </tr>
            <tr>
                <th>CreatedAt</th>
                <td>{{ event.createdAt ? event.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>UpdatedAt</th>
                <td>{{ event.updatedAt ? event.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>CreatedUsername</th>
                <td>{{ event.createdUsername }}</td>
            </tr>
            <tr>
                <th>UpdatedUsername</th>
                <td>{{ event.updatedUsername }}</td>
            </tr>
            <tr>
                <th>Organizer</th>
                <td>{{ event.organizer }}</td>
            </tr>
            <tr>
                <th>StartDateTime</th>
                <td>{{ event.startDateTime ? event.startDateTime|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>End_datetime</th>
                <td>{{ event.endDatetime ? event.endDatetime|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_event_index') }}">back to list</a>


    {{ include('event/_delete_form.html.twig') }}
{% endblock %}